Referencing fields
ConduitIO/conduit-site pull request #50
Opened 2024-03-08 14:53 UTC by hariso

2024-03-09 09:25 UTC, raulb approved these changes
Nice! @hariso Great call already pointing out to the page that will be added as part of https://github.com/ConduitIO/conduit-site/pull/49. Will make sure I ship that one soon so we can ship this one without a broken link.

2024-03-09 11:01 UTC, raulb requested changes
I just realized that we need to link differently to this page.

2024-03-09 11:01 UTC, raulb commented on docs/processors/referencing-fields.mdx
> +the [OpenCDC format](/docs/features/opencdc-record.mdx)). That is done through
I just realized about this.

```suggestion
the [OpenCDC format](/docs/features/opencdc-record)). That is done through
```

2024-03-11 18:39 UTC, maha-hajja commented on docs/processors/referencing-fields.mdx
> +Very often, processors can be configured to work on a specific field in a
I think we should also mention that these references are how the fields would be addressed in a Go template, and maybe add a link for go templates format

2024-03-13 08:08 UTC, raulb approved these changes
Looks great. I really like having both the json and the dot notation side by side, extending this information below. Great work 👌

2024-03-13 12:00 UTC, merged